export default {
    /* Search */
    SEARCH: 'SEARCH',
    CHANGE_VERTICAL: 'CHANGE_VERTICAL',
    CHANGE_PAGE: 'CHANGE_PAGE',
    OPEN_URL: 'OPEN_URL',
    CLOSE_URL: 'CLOSE_URL',

    /* Features */
    GET_QUERY_HISTORY: 'GET_QUERY_HISTORY',
    GET_BOOKMARKS: 'GET_BOOKMARKS',
    ADD_BOOKMARK: 'ADD_BOOKMARK',
    REMOVE_BOOKMARK: 'REMOVE_BOOKMARK',
    STAR_BOOKMARK: 'STAR_BOOKMARK',
    GET_ANNOTATIONS: 'GET_ANNOTATIONS',
    ADD_ANNOTATION: 'ADD_ANNOTATION',
    REMOVE_ANNOTATION: 'REMOVE_ANNOTATION',
    GET_RATING: 'GET_RATING',
    SUBMIT_RATING: 'SUBMIT_RATING'
}