export default {
    /* Search */
    SEARCH: 'SEARCH',
    CHANGE_VERTICAL: 'CHANGE_VERTICAL',
    CHANGE_PAGE: 'CHANGE_PAGE',
    UPDATE_METADATA: 'UPDATE_METADATA',
    OPEN_URL: 'OPEN_URL',
    CLOSE_URL: 'CLOSE_URL',
    GET_DOCUMENT_BY_ID: 'GET_DOCUMENT_BY_ID',
    RESET: 'RESET',
    CHANGE_VARIANT: 'VARIANT',

    /* Features */
    GET_QUERY_HISTORY: 'GET_QUERY_HISTORY',
    GET_BOOKMARKS_AND_EXCLUDES: 'GET_BOOKMARKS_AND_EXCLUDES',
    ADD_BOOKMARK: 'ADD_BOOKMARK',
    REMOVE_BOOKMARK: 'REMOVE_BOOKMARK',
    GET_EXCLUDES: 'GET_EXCLUDES',
    ADD_EXCLUDE: 'ADD_EXCLUDE',
    REMOVE_EXCLUDE: 'REMOVE_EXCLUDE',
    STAR_BOOKMARK: 'STAR_BOOKMARK',
    GET_ANNOTATIONS: 'GET_ANNOTATIONS',
    ADD_ANNOTATION: 'ADD_ANNOTATION',
    REMOVE_ANNOTATION: 'REMOVE_ANNOTATION',
    GET_RATING: 'GET_RATING',
    SUBMIT_RATING: 'SUBMIT_RATING'
}