export const LoggerEventTypes = {
    // SEARCH
    SEARCH_QUERY: 'SEARCH_QUERY',
    SEARCH_CHANGE_VERTICAL: 'SEARCH_CHANGE_VERTICAL',
    SEARCH_CHANGE_PAGE: 'SEARCH_CHANGE_PAGE',
    SEARCH_SHOW_ALL_COLLAPSED: 'SEARCH_SHOW_ALL_COLLAPSED',
    SEARCH_HIDE_ALL_COLLAPSED: 'SEARCH_HIDE_ALL_COLLAPSED',
    SEARCHRESULT_CLICK_URL: 'SEARCHRESULT_CLICK_URL',
    SEARCHRESULT_CONTEXT_URL: 'SEARCHRESULT_CONTEXT_URL',
    SEARCHRESULT_VIEW_URL: 'SEARCHRESULT_VIEW_URL',
    SEARCHRESULT_HOVERENTER: 'SEARCHRESULT_HOVERENTER',
    SEARCHRESULT_HOVERLEAVE: 'SEARCHRESULT_HOVERLEAVE',
    SEARCHRESULT_VIDEO: 'SEARCHRESULT_VIDEO',
    SEARCHRESULT_ELAPSEDTIME: 'SEARCHRESULT_ELAPSEDTIME',
    SEARCHRESULT_SHOW_COLLAPSED: 'SEARCHRESULT_SHOW_COLLAPSED',
    SEARCHRESULT_HIDE_COLLAPSED: 'SEARCHRESULT_HIDE_COLLAPSED',
    DOCUMENT_HOVERENTER: 'DOCUMENT_HOVERENTER',
    DOCUMENT_HOVERLEAVE: 'DOCUMENT_HOVERLEAVE',
    DOCUMENT_LOAD: 'DOCUMENT_LOAD',
    DOCUMENT_CLOSE: 'DOCUMENT_CLOSE',
    DOCUMENT_OPEN_BROWSER: 'DOCUMENT_OPEN_BROWSER',
    DOCUMENT_SCROLL: 'DOCUMENT_SCROLL',
    SEARCH_EXIT: 'SEARCH_EXIT',

    // SURVEY
    SURVEY_REGISTER_RESULTS: 'SURVEY_REGISTER_RESULTS',
    SURVEY_PRE_TEST_RESULTS: 'SURVEY_PRE_TEST_RESULTS',
    SURVEY_INTERMEDIATE_TEST_RESULTS: 'SURVEY_INTERMEDIATE_TEST_RESULTS',
    SURVEY_POST_TEST_RESULTS: 'SURVEY_POST_TEST_RESULTS',
    SURVEY_GROUP_WAIT_FINISH: 'SURVEY_GROUP_WAIT_FINISH',
    SURVEY_GROUPING_TIMEOUT: 'SURVEY_GROUPING_TIMEOUT',
    SURVEY_INTRO_START: 'SURVEY_INTRO_START',
    SURVEY_INTRO_END: 'SURVEY_INTRO_END',
    SURVEY_LEARNING_START: 'SURVEY_LEARNING_START',
    SURVEY_LEARNING_DONE: 'SURVEY_LEARNING_DONE',
    SURVEY_LEARNING_VIDEO: 'SURVEY_LEARNING_VIDEO',
    SURVEY_EXIT: 'SURVEY_EXIT',

    // TASK,

    TASK_OPEN: 'TASK_OPEN',
    TASK_CLOSE: 'TASK_CLOSE',
    TASK_DESCRIPTION_LOAD: 'TASK_DESCRIPTION_LOAD',
    TASK_DESCRIPTION_CONTINUE: 'TASK_DESCRIPTION_CONTINUE',

    // SESSION
    WINDOW_CHANGE_VISIBILITY: 'WINDOW_CHANGE_VISIBILITY',
    SESSION_START: 'SESSION_START',
    SESSION_END: 'SESSION_END',

    // FEATURE
    BOOKMARK_ACTION: 'BOOKMARK_ACTION',
    EXCLUDE_ACTION: 'EXCLUDE_ACTION',
    BOOKMARK_CLICK_URL: 'BOOKMARK_CLICK_URL',
    BOOKMARK_CONTEXT_URL: 'BOOKMARK_CONTEXT_URL',
    BOOKMARK_HOVERENTER: 'BOOKMARK_HOVERENTER',
    BOOKMARK_HOVERLEAVE: 'BOOKMARK_HOVERLEAVE',
    CHAT_MESSAGE: 'CHAT_MESSAGE',
    CHAT_CLICK: 'CHAT_CLICK',
    QUERYHISTORY_CLICK_URL: 'QUERYHISTORY_CLICK_URL',
    QUERYHISTORY_CONTEXT_URL: 'QUERYHISTORY_CONTEXT_URL',
    QUERYHISTORY_HOVERENTER: 'QUERYHISTORY_HOVERENTER',
    QUERYHISTORY_HOVERLEAVE: 'QUERYHISTORY_HOVERLEAVE',
    TETRIS_OPEN: 'TETRIS_OPEN',
    TETRIS_CLOSE: 'TETRIS_CLOSE',
    QUERYSUGGESTIONS_GET: 'QUERYSUGGESTIONS_GET',
    QUERYSUGGESTION_CLICK_URL: 'QUERYSUGGESTION_CLICK_URL',
    QUERYSUGGESTION_CONTEXT_URL: 'QUERYSUGGESTION_CONTEXT_URL',
    QUERYSUGGESTION_HOVERENTER: 'QUERYSUGGESTION_HOVERENTER',
    QUERYSUGGESTION_HOVERLEAVE: 'QUERYSUGGESTION_HOVERLEAVE',

    // TAB CHANGE LOG
    TAB_CHANGE: 'TAB_CHANGE'

};