export const LoggerEventTypes = {
    // SEARCH
    SEARCH_QUERY: 'SEARCH_QUERY',
    SEARCH_CHANGE_VERTICAL: 'SEARCH_CHANGE_VERTICAL',
    SEARCH_CHANGE_PAGE: 'SEARCH_CHANGE_PAGE',
    SEARCHRESULT_CLICK_URL: 'SEARCHRESULT_CLICK_URL',
    SEARCHRESULT_CONTEXT_URL: 'SEARCHRESULT_CONTEXT_URL',
    SEARCHRESULT_VIEW_URL: 'SEARCHRESULT_VIEW_URL',
    SEARCHRESULT_HOVERENTER: 'SEARCHRESULT_HOVERENTER',
    SEARCHRESULT_HOVERLEAVE: 'SEARCHRESULT_HOVERLEAVE',
    SEARCHRESULT_VIDEO: 'SEARCHRESULT_VIDEO',
    SEARCHRESULT_ELAPSEDTIME: 'SEARCHRESULT_ELAPSEDTIME',

    // SURVEY
    SURVEY_REGISTER_RESULTS: 'SURVEY_REGISTER_RESULTS',
    SURVEY_PRE_TEST_RESULTS: 'SURVEY_PRE_TEST_RESULTS',
    SURVEY_POST_TEST_RESULTS: 'SURVEY_POST_TEST_RESULTS',
    SURVEY_GROUPING_TIMEOUT: 'SURVEY_GROUPING_TIMEOUT',
    SURVEY_INTRO_START: 'SURVEY_INTRO_START',
    SURVEY_LEARNING_START: 'SURVEY_LEARNING_START',
    SURVEY_LEARNING_DONE: 'SURVEY_LEARNING_DONE',
    SURVEY_LEARNING_VIDEO: 'SURVEY_LEARNING_VIDEO',
    SURVEY_EXIT: 'SURVEY_EXIT',

    // WINDOW
    WINDOW_CHANGE_VISIBILITY: 'WINDOW_CHANGE_VISIBILITY',

    // SESSION
    BOOKMARK_CLICK_URL: 'BOOKMARK_CLICK_URL',
    BOOKMARK_CONTEXT_URL: 'BOOKMARK_CONTEXT_URL',
    BOOKMARK_HOVERENTER: 'BOOKMARK_HOVERENTER',
    BOOKMARK_HOVERLEAVE: 'BOOKMARK_HOVERLEAVE',
    CHAT_ARCHIVE: 'CHAT_ARCHIVE',
    QUERYHISTORY_CLICK_URL: 'QUERYHISTORY_CLICK_URL',
    QUERYHISTORY_CONTEXT_URL: 'QUERYHISTORY_CONTEXT_URL',
    QUERYHISTORY_HOVERENTER: 'QUERYHISTORY_HOVERENTER',
    QUERYHISTORY_HOVERLEAVE: 'QUERYHISTORY_HOVERLEAVE',
};