export default {
    /* Search constants */
    SEARCH: 'SEARCH',
    CHANGE_VERTICAL: 'CHANGE_VERTICAL',
    CHANGE_QUERY: 'CHANGE_QUERY',
    NEXT_PAGE: 'NEXT_PAGE',
    REFRESH_SEARCH: 'REFRESH_SEARCH',

    /* Account constants */
    UPDATE_ACCOUNT_DETAILS: 'UPDATE_ACCOUNT_DETAILS',

    /* Bookmark constants */
    GET_BOOKMARKS: 'GET_BOOKMARKS',
    ADD_BOOKMARK: 'ADD_BOOKMARK',
    REMOVE_BOOKMARK: 'REMOVE_BOOKMARK'
}