export default {
    /* Search constants */
    SEARCH: 'SEARCH',
    CHANGE_VERTICAL: 'CHANGE_VERTICAL',
    CHANGE_QUERY: 'CHANGE_QUERY',
    NEXT_PAGE: 'NEXT_PAGE',
    REFRESH_SEARCH: 'REFRESH_SEARCH',

    /* Session constants */
    GET_QUERY_HISTORY: 'GET_QUERY_HISTORY',
    GET_BOOKMARKS: 'GET_BOOKMARKS',
    ADD_BOOKMARK: 'ADD_BOOKMARK',
    REMOVE_BOOKMARK: 'REMOVE_BOOKMARK'
}