export const LoggerEventTypes = {
    // SEARCH
    SEARCHBOX_CHANGE_VERTICAL: 'SEARCHBOX_CHANGE_VERTICAL',
    SEARCHBOX_SEARCH: 'SEARCHBOX_SEARCH',
    SEARCHRESULT_CLICK_URL: 'SEARCHRESULT_CLICK_URL',
    SEARCHRESULT_CONTEXT_URL: 'SEARCHRESULT_CONTEXT_URL',
    SEARCHRESULT_VIEW_URL: 'SEARCHRESULT_VIEW_URL',
    SEARCHRESULTS_NEXT_PAGE: 'SEARCHRESULTS_NEXT_PAGE',
    SEARCHRESULT_HOVERENTER: 'SEARCHRESULT_HOVERENTER',
    SEARCHRESULT_HOVERLEAVE: 'SEARCHRESULT_HOVERLEAVE',
    SEARCHRESULT_VIDEO: 'SEARCHRESULT_VIDEO',
    SEARCHRESULT_ELAPSEDTIME: 'SEARCHRESULT_ELAPSEDTIME',

    // SURVEY
    CHANGE_VISIBILITY: 'CHANGE_VISIBILITY',
    SURVEY_REGISTER_RESULTS: 'SURVEY_REGISTER_RESULTS',
    SURVEY_PRE_TEST_RESULTS: 'SURVEY_PRE_TEST_RESULTS',
    SURVEY_POST_TEST_RESULTS: 'SURVEY_POST_TEST_RESULTS',
    SURVEY_LEARNING_VIDEO: 'SURVEY_LEARNING_VIDEO',
    SURVEY_LEARNING_DONE: 'SURVEY_LEARNING_DONE',
    SURVEY_LEARNING_START: 'SURVEY_LEARNING_START',



    BOOKMARK_CLICK_URL: 'BOOKMARK_CLICK_URL',
    BOOKMARK_CONTEXT_URL: 'BOOKMARK_CONTEXT_URL',
    BOOKMARK_HOVERENTER: 'BOOKMARK_HOVERENTER',
    BOOKMARK_HOVERLEAVE: 'BOOKMARK_HOVERLEAVE'

};